### ISSUE TITLE
LoadError: libmariadb.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by deepakmahakale** [basecamp/kamal#1069]
I am unable to deploy the mysql accessory.

I have the following in **Dockerfile**
```
# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential default-libmysqlclient-dev git pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
```

I tried this too
```
# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential mariadb-client libmariadb-dev git pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
```

**Gemfile**
```ruby
# Use mysql2 as the database for Active Record
gem "mysql2", "~> 0.5"
```

Content from **deploy.yml**
```yml
env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_ROOT_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: kamal-demo-blog-db

accessories:
  db:
    image: mysql:8.0
    host: 37.xx.xxx.5
    port: "127.0.0.1:3306:3306"
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
      secret:
        - MYSQL_ROOT_PASSWORD
    files:
      # - config/mysql/production.cnf:/etc/mysql/my.cnf
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/mysql
```

```
2024-10-07T07:26:47.638164222Z LoadError: libmariadb.so.3: cannot open shared object file: No such file or directory - /usr/local/bundle/ruby/3.2.0/gems/mysql2-0.5.6/lib/mysql2/mysql2.so (LoadError)
2024-10-07T07:26:47.638733761Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-10-07T07:26:47.638755349Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-10-07T07:26:47.638763328Z /usr/local/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2024-10-07T07:26:47.638770754Z /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
2024-10-07T07:26:47.638777852Z /usr/local/bundle/ruby/3.2.0/gems/mysql2-0.5.6/lib/mysql2.rb:36:in `<main>'
2024-10-07T07:26:47.638785200Z /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
2024-10-07T07:26:47.638825831Z /usr/local/bundle/ruby/3.2.0/gems/zeitwerk-2.6.18/lib/zeitwerk/kernel.rb:34:in `require'
2024-10-07T07:26:47.638833100Z /rails/config/application.rb:7:in `<main>'
2024-10-07T07:26:47.638840334Z /rails/Rakefile:4:in `require_relative'
2024-10-07T07:26:47.638847275Z /rails/Rakefile:4:in `<main>'
2024-10-07T07:26:47.638863028Z /usr/local/bundle/ruby/3.2.0/gems/railties-8.0.0.beta1/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
2024-10-07T07:26:47.638870760Z /usr/local/bundle/ruby/3.2.0/gems/railties-8.0.0.beta1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
2024-10-07T07:26:47.638907686Z /usr/local/bundle/ruby/3.2.0/gems/railties-8.0.0.beta1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
2024-10-07T07:26:47.638916032Z /usr/local/bundle/ruby/3.2.0/gems/railties-8.0.0.beta1/lib/rails/command.rb:156:in `invoke_rake'
2024-10-07T07:26:47.638923325Z /usr/local/bundle/ruby/3.2.0/gems/railties-8.0.0.beta1/lib/rails/command.rb:73:in `block in invoke'
2024-10-07T07:26:47.638930476Z /usr/local/bundle/ruby/3.2.0/gems/railties-8.0.0.beta1/lib/rails/command.rb:149:in `with_argv'
2024-10-07T07:26:47.638937797Z /usr/local/bundle/ruby/3.2.0/gems/railties-8.0.0.beta1/lib/rails/command.rb:69:in `invoke'
2024-10-07T07:26:47.638945283Z /usr/local/bundle/ruby/3.2.0/gems/railties-8.0.0.beta1/lib/rails/commands.rb:18:in `<main>'
2024-10-07T07:26:47.638952603Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-10-07T07:26:47.638960016Z <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-10-07T07:26:47.638994583Z /usr/local/bundle/ruby/3.2.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
2024-10-07T07:26:47.639002488Z ./bin/rails:4:in `<main>'
2024-10-07T07:26:47.639010147Z (See full trace by running task with --trace)
2024-10-07T07:26:48.947926319Z bin/rails aborted!
```

### Update

Even with postgres I am getting similar error

```
2024-10-07T07:58:25.839875446Z LoadError: libpq.so.5: cannot open shared object file: No such file or directory - /usr/local/bundle/ruby/3.2.0/gems/pg-1.5.8/lib/pg_ext.so (LoadError)
```

**Comment by deepakmahakale** [comment]
This old blog helped

https://kyrylo.org/rails/kamal/2024/01/17/making-postgresql-work-with-kamal-and-a-new-rails-7-1-application.html

All I had to do was add `libpq-dev` (in case of postgres) in two places

```dockerfile
# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips libpq-dev && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
.
.
.
# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives
```

**Comment by deepakmahakale** [comment]
This is solved

This was caused as the task `rails db:system:change --to=mysql` didn't work properly and there required packages were not getting added properly

I am raising a pr to rails
