### ISSUE TITLE
FIDO2/ed25519-sk key reported as invalid

### ISSUE THREAD

**Issue by ofekd** [basecamp/kamal#1131]
I am using an ed25519-sk key as per the Yubikey docs:

https://developers.yubico.com/SSH/

It works fine running the `ssh` command. Relevant logs suggest the SSH used may be too old:

```
D, [2024-10-18T04:49:05.793655 #998330] DEBUG -- net.ssh.transport.server_version[7f8]: local is `SSH-2.0-Ruby/Net::SSH_7.3.0 x86_64-linux'
D, [2024-10-18T04:49:05.882180 #998330] DEBUG -- net.ssh.transport.server_version[7f8]: remote is `SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.5'
....
E, [2024-10-18T04:49:06.449335 #998330] ERROR -- net.ssh.authentication.key_manager[85c]: could not load public key file `/<redacted>/.ssh/id_ed25519_sk.pub': Net::SSH::Exception (public key at /<redacted>/.ssh/id_ed25519_sk.pub is not valid)
```

I wonder if it could be updated, if I could update it myself locally, or maybe use the ssh version installed on my computed.

I do not use ssh-agent.

As a workaround, I've reverted to a regular key

**Comment by djmb** [comment]
I'm not 100% sure but this may be a limitation of net-ssh (see https://github.com/net-ssh/net-ssh/issues/954https://github.com/net-ssh/net-ssh/issues/954).

Can you ssh directly with the ssh command using the ed25519-sk key?

**Comment by ofekd** [comment]
Yes, the SSH command works well

**Comment by djmb** [comment]
I think then we are stuck until net-ssh adds support.

**Comment by ofekd** [comment]
It is what it is -- thanks for checking

**Comment by Thrizian** [comment]
I´d like to add to this that this did work for me in ruby 3.4.1 | rails 8.0.1 using simply Net::SSH

```ruby
Net::SSH.start('MY-SERVER-IP', 'root', keys: ['/home/my-name/.ssh/id_ed25519'], verbose: :debug) do |ssh|
    puts ssh.exec!('echo SSH connection successful!')
end
```

When Kamal does it, it doesn´t work.

```
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/ed25519-1.3.0/lib/ed25519.rb:44:in 'Ed25519.validate_key_bytes'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/ed25519-1.3.0/lib/ed25519/verify_key.rb:10:in 'Ed25519::VerifyKey#initialize'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/authentication/ed25519.rb:110:in 'Class#new'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/authentication/ed25519.rb:110:in 'Net::SSH::Authentication::ED25519::PubKey#initialize'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/authentication/ed25519.rb:114:in 'Class#new'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/authentication/ed25519.rb:114:in 'Net::SSH::Authentication::ED25519::PubKey.read_keyblob'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/buffer.rb:338:in 'Net::SSH::Buffer#read_keyblob'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/buffer.rb:248:in 'Net::SSH::Buffer#read_key'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:109:in 'SSHKit::Backend::Netssh::KnownHostsKeys#parse_key'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:76:in 'SSHKit::Backend::Netssh::KnownHostsKeys#parse_line'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:63:in 'block (3 levels) in SSHKit::Backend::Netssh::KnownHostsKeys#parse_file'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:61:in 'IO#each_line'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:61:in 'block (2 levels) in SSHKit::Backend::Netssh::KnownHostsKeys#parse_file'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:59:in 'IO.open'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:59:in 'block in SSHKit::Backend::Netssh::KnownHostsKeys#parse_file'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:48:in 'Thread::Mutex#synchronize'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:48:in 'SSHKit::Backend::Netssh::KnownHostsKeys#parse_file'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:19:in 'SSHKit::Backend::Netssh::KnownHostsKeys#keys_for'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:122:in 'block in SSHKit::Backend::Netssh::KnownHosts#search_for'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:121:in 'Array#map'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh/known_hosts.rb:121:in 'SSHKit::Backend::Netssh::KnownHosts#search_for'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/session.rb:97:in 'Net::SSH::Transport::Session#host_keys'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/verifiers/always.rb:17:in 'Net::SSH::Verifiers::Always#verify'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/verifiers/accept_new.rb:17:in 'Net::SSH::Verifiers::AcceptNew#verify'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/verifiers/accept_new_or_local_tunnel.rb:17:in 'Net::SSH::Verifiers::AcceptNewOrLocalTunnel#verify'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/kex/abstract.rb:82:in 'Net::SSH::Transport::Kex::Abstract#verify_server_key'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/kex/abstract.rb:49:in 'Net::SSH::Transport::Kex::Abstract#exchange_keys'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/algorithms.rb:458:in 'Net::SSH::Transport::Algorithms#exchange_keys'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/algorithms.rb:257:in 'Net::SSH::Transport::Algorithms#proceed!'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/algorithms.rb:196:in 'Net::SSH::Transport::Algorithms#accept_kexinit'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/session.rb:210:in 'block in Net::SSH::Transport::Session#poll_message'
<internal:kernel>:168:in 'Kernel#loop'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/session.rb:190:in 'Net::SSH::Transport::Session#poll_message'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/session.rb:227:in 'block in Net::SSH::Transport::Session#wait'
<internal:kernel>:168:in 'Kernel#loop'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/session.rb:224:in 'Net::SSH::Transport::Session#wait'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh/transport/session.rb:89:in 'Net::SSH::Transport::Session#initialize'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh.rb:258:in 'Class#new'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/net-ssh-7.3.0/lib/net/ssh.rb:258:in 'Net::SSH.start'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/kamal-2.4.0/lib/kamal/sshkit_with_ext.rb:97:in 'block in SSHKit::Backend::Netssh::LimitConcurrentStartsInstance#start_with_concurrency_limit'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/concurrent-ruby-1.3.5/lib/concurrent-ruby/concurrent/atomic/mutex_semaphore.rb:31:in 'Concurrent::MutexSemaphore#acquire'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/kamal-2.4.0/lib/kamal/sshkit_with_ext.rb:96:in 'SSHKit::Backend::Netssh::LimitConcurrentStartsInstance#start_with_concurrency_limit'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/connection_pool.rb:63:in 'Method#call'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/connection_pool.rb:63:in 'SSHKit::Backend::ConnectionPool#with'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/kamal-2.4.0/lib/kamal/sshkit_with_ext.rb:85:in 'SSHKit::Backend::Netssh::LimitConcurrentStartsInstance#with_ssh'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/netssh.rb:145:in 'SSHKit::Backend::Netssh#execute_command'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/abstract.rb:148:in 'block in SSHKit::Backend::Abstract#create_command_and_execute'
<internal:kernel>:91:in 'Kernel#tap'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/abstract.rb:148:in 'SSHKit::Backend::Abstract#create_command_and_execute'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/abstract.rb:80:in 'SSHKit::Backend::Abstract#execute'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/kamal-2.4.0/lib/kamal/cli/registry.rb:7:in 'block in Kamal::Cli::Registry#login'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/abstract.rb:31:in 'BasicObject#instance_exec'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/sshkit-1.23.2/lib/sshkit/backends/abstract.rb:31:in 'SSHKit::Backend::Abstract#run'
/home/username/.asdf/installs/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/kamal-2.4.0/lib/kamal/sshkit_with_ext.rb:118:in 'block (2 levels) in SSHKit::Runner::Parallel::CompleteAll#execute'
```
