### ISSUE TITLE
Deployment broken with OpenSSL 3.1.3 19 Sep 2023 (Library: OpenSSL 3.1.3 19 Sep 2023)

### ISSUE THREAD

**Issue by intrip** [basecamp/kamal#539]
We encountered the following deployment error when deploying with Kamal using OpenSSL 3.1.3

```
Running the pre-connect hook...
  INFO [f2ccdac5] Running /usr/bin/env .kamal/hooks/pre-connect as rosa@localhost
 DEBUG [f2ccdac5] Command: ( export KAMAL_RECORDED_AT="2023-10-20T15:38:22Z" KAMAL_PERFORMER="rosa" KAMAL_DESTINATION="beta1" KAMAL_VERSION="817596d81b47c36db087c0d7505f884f3e24ad27" KAMAL_SERVICE_VERSION="hey@817596d" KAMAL_HOSTS="hey-beta-app-101,hey-beta-jobs-101" KAMAL_COMMAND="deploy" ; /usr/bin/env .kamal/hooks/pre-connect )
 DEBUG [f2ccdac5] 	Prewarmed 3 DNS lookups in 0.64 sec: 0 retries, 0 failures
  INFO [f2ccdac5] Finished in 0.756 seconds with exit status 0 (successful).
  INFO [42c181d3] Running /usr/bin/env mkdir -p .kamal on hey-beta-app-101
 DEBUG [42c181d3] Command: /usr/bin/env mkdir -p .kamal
  INFO [3562acc1] Running /usr/bin/env mkdir -p .kamal on hey-beta-jobs-101
 DEBUG [3562acc1] Command: /usr/bin/env mkdir -p .kamal
  Finished all in 1.6 seconds
  ERROR (OpenSSL::PKey::EC::Point::Error): Exception while executing on host hey-beta-app-101: EC_POINT_bn2point: invalid encoding
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/openssl.rb:164:in `initialize'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/openssl.rb:164:in `new'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/openssl.rb:164:in `read_keyblob'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/buffer.rb:340:in `read_keyblob'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/buffer.rb:248:in `read_key'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:108:in `parse_key'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:75:in `parse_line'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:62:in `block (3 levels) in parse_file'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:60:in `each_line'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:60:in `block (2 levels) in parse_file'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:58:in `open'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:58:in `block in parse_file'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/3.3.0+0/mutex_m.rb:77:in `synchronize'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/3.3.0+0/mutex_m.rb:77:in `mu_synchronize'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:47:in `parse_file'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:18:in `keys_for'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:122:in `block in search_for'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:121:in `map'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh/known_hosts.rb:121:in `search_for'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/session.rb:97:in `host_keys'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/verifiers/always.rb:17:in `verify'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/verifiers/accept_new.rb:17:in `verify'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/verifiers/accept_new_or_local_tunnel.rb:17:in `verify'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/kex/abstract.rb:82:in `verify_server_key'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/kex/abstract.rb:49:in `exchange_keys'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/algorithms.rb:454:in `exchange_keys'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/algorithms.rb:253:in `proceed!'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/algorithms.rb:192:in `accept_kexinit'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
<internal:kernel>:187:in `loop'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/session.rb:190:in `poll_message'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/session.rb:227:in `block in wait'
<internal:kernel>:187:in `loop'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/session.rb:224:in `wait'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh/transport/session.rb:89:in `initialize'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh.rb:256:in `new'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/bundler/gems/net-ssh-efd0ebe882fc/lib/net/ssh.rb:256:in `start'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/kamal-1.0.0/lib/kamal/sshkit_with_ext.rb:95:in `block in start_with_concurrency_limit'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/atomic/mutex_semaphore.rb:31:in `acquire'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/kamal-1.0.0/lib/kamal/sshkit_with_ext.rb:94:in `start_with_concurrency_limit'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/connection_pool.rb:63:in `call'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/connection_pool.rb:63:in `with'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/kamal-1.0.0/lib/kamal/sshkit_with_ext.rb:83:in `with_ssh'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/netssh.rb:130:in `execute_command'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
<internal:kernel>:90:in `tap'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:80:in `execute'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/kamal-1.0.0/lib/kamal/cli/base.rb:175:in `block in ensure_run_directory'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/backends/abstract.rb:31:in `run'
/Users/rosa/.rbenv/versions/3.3.0-preview2/lib/ruby/gems/3.3.0+0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
```

Looks like `net-ssh` doesn't work well with the latest openssl?

**Comment by rosa** [comment]
Ok, so, after a few hours debugging, deep into `kamal`, `sshkit`, and `net-ssh`, looking into all sort of things, I decided to delete `~/.ssh/known_host` completely (I had previously tried to remove the entries corresponding to the problematic hosts only), as I wanted a minimal reproduction case without worrying about known hosts, and guess what? It fixed itself! The only problem is that I won't know now what was wrong, but clearly it was something there that was making `Net::SSH::Buffer#read_string` to somehow miss a few bytes at the end of a public key, resulting in that encoding error. 
Oh well. I imagine this is much better than some obscure bug in `net-ssh`!
