### ISSUE TITLE
Unsupported Key type `kamal env push`

### ISSUE THREAD

**Issue by danvixent** [basecamp/kamal#871]
Hi, i was initially using kamal version 1.1.0, which always worked well. Then recently, I ran `kamal env push` but I got this trace:

```bash
$HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.3/lib/net/ssh/buffer.rb:342:in `read_keyblob': unsupported key type `���Q=�;̫>��D��r�t��b��' (NotImplementedError)
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.3/lib/net/ssh/buffer.rb:248:in `read_key'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:109:in `parse_key'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:76:in `parse_line'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:63:in `block (3 levels) in parse_file'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:61:in `each_line'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:61:in `block (2 levels) in parse_file'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:59:in `open'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:59:in `block in parse_file'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:48:in `synchronize'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:48:in `parse_file'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:19:in `keys_for'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:122:in `block in search_for'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:121:in `map'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh/known_hosts.rb:121:in `search_for'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.3/lib/net/ssh/transport/session.rb:97:in `host_keys'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.3/lib/net/ssh/transport/algorithms.rb:285:in `prepare_preferred_algorithms!'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.3/lib/net/ssh/transport/algorithms.rb:161:in `initialize'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.3/lib/net/ssh/transport/session.rb:87:in `new'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.3/lib/net/ssh/transport/session.rb:87:in `initialize'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.3/lib/net/ssh.rb:258:in `new'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/net-ssh-7.2.3/lib/net/ssh.rb:258:in `start'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.7.3/lib/kamal/sshkit_with_ext.rb:96:in `block in start_with_concurrency_limit'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/concurrent-ruby-1.3.3/lib/concurrent-ruby/concurrent/atomic/mutex_semaphore.rb:31:in `acquire'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.7.3/lib/kamal/sshkit_with_ext.rb:95:in `start_with_concurrency_limit'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/connection_pool.rb:63:in `call'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/connection_pool.rb:63:in `with'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.7.3/lib/kamal/sshkit_with_ext.rb:84:in `with_ssh'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/netssh.rb:145:in `execute_command'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
        from <internal:kernel>:90:in `tap'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/abstract.rb:80:in `execute'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.7.3/lib/kamal/cli/base.rb:189:in `block in ensure_run_and_locks_directory'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
        from $HOME/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sshkit-1.23.0/lib/sshkit/backends/abstract.rb:31:in `run'
        from $HOME
```

I decided to update kamal with `gem update kamal` to version  `1.7.3` but still the same issue. I have also tried switching the ssh key  defined for my hosts in the ssh config from rsa to ed25519. So effectively this Is happening for both RSA private keys & ed25519 private keys. I'm not sure why this keeps happening. Does anyone have any pointers?

**Comment by djmb** [comment]
Closing as this is for Kamal 1.0
