### ISSUE TITLE
[1.7.3] undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by hrstoyanov** [basecamp/kamal#874]
>kamal env push

```
  INFO [0c3e9d0b] Running /usr/bin/env mkdir -p .kamal on ts1.possum-mountain.ts.net
 DEBUG [0c3e9d0b] Command: /usr/bin/env mkdir -p .kamal
  INFO [0c3e9d0b] Finished in 0.069 seconds with exit status 0 (successful).
  INFO [cd397859] Running /usr/bin/env mkdir -p .kamal/locks on ts1.possum-mountain.ts.net
 DEBUG [cd397859] Command: /usr/bin/env mkdir -p .kamal/locks
  INFO [cd397859] Finished in 0.030 seconds with exit status 0 (successful).
Acquiring the deploy lock...
 DEBUG [9e420e5d] Running /usr/bin/env mkdir .kamal/locks/inswebapp && echo "TG9ja2VkIGJ5OiAgYXQgMjAyNC0wNy0wNVQwNjo1NDo1MloKVmVyc2lvbjog
MDdiMWUwMWEyMmUwZGVhNTY4OWI0NzZhNTVkZmM4ZGZlNjlmMTc0OApNZXNz
YWdlOiBBdXRvbWF0aWMgZGVwbG95IGxvY2s=
" > .kamal/locks/inswebapp/details on ts1.possum-mountain.ts.net
 DEBUG [9e420e5d] Command: /usr/bin/env mkdir .kamal/locks/inswebapp && echo "TG9ja2VkIGJ5OiAgYXQgMjAyNC0wNy0wNVQwNjo1NDo1MloKVmVyc2lvbjog
MDdiMWUwMWEyMmUwZGVhNTY4OWI0NzZhNTVkZmM4ZGZlNjlmMTc0OApNZXNz
YWdlOiBBdXRvbWF0aWMgZGVwbG95IGxvY2s=
" > .kamal/locks/inswebapp/details
 DEBUG [9e420e5d] Finished in 0.036 seconds with exit status 0 (successful).
 DEBUG [e208cf98] Running /usr/bin/env echo [2024-07-05T06:54:52Z] [root] Pushed env files >> .kamal/inswebapp-audit.log on ts1.possum-mountain.ts.net
 DEBUG [e208cf98] Command: /usr/bin/env echo [2024-07-05T06:54:52Z] [root] Pushed env files >> .kamal/inswebapp-audit.log
 DEBUG [e208cf98] Finished in 0.028 seconds with exit status 0 (successful).
Releasing the deploy lock...
 DEBUG [e8f1fd11] Running /usr/bin/env rm .kamal/locks/inswebapp/details && rm -r .kamal/locks/inswebapp on ts1.possum-mountain.ts.net
 DEBUG [e8f1fd11] Command: /usr/bin/env rm .kamal/locks/inswebapp/details && rm -r .kamal/locks/inswebapp
 DEBUG [e8f1fd11] Finished in 0.025 seconds with exit status 0 (successful).
  ERROR (NoMethodError): Exception while executing on host ts1.possum-mountain.ts.net: undefined method `[]' for nil:NilClass
/usr/local/bundle/gems/kamal-1.7.3/lib/kamal/configuration.rb:225:in `env_tags'
/usr/local/bundle/gems/kamal-1.7.3/lib/kamal/configuration.rb:233:in `env_tag'
/usr/local/bundle/gems/kamal-1.7.3/lib/kamal/configuration/role.rb:42:in `block in env_tags'

```

**Comment by acidtib** [comment]
hi @hrstoyanov can you share your deploy.yml

**Comment by acidtib** [comment]
Based on the error log and the deploy.yml file, it appears that a host is being tagged with `dev` without an environment being defined for that tag. This causes Kamal to fail because it cannot read the environment settings for the `dev` tag, as it does not yet exist in deploy.yml.

```
 ERROR (NoMethodError): Exception while executing on host ts1.possum-mountain.ts.net: undefined method `[]' for nil:NilClass
/usr/local/bundle/gems/kamal-1.7.3/lib/kamal/configuration.rb:225:in `env_tags'
/usr/local/bundle/gems/kamal-1.7.3/lib/kamal/configuration.rb:233:in `env_tag'
/usr/local/bundle/gems/kamal-1.7.3/lib/kamal/configuration/role.rb:42:in `block in env_tags'
```


check out this section in the documentation it will help you define the envs using tags
https://kamal-deploy.org/docs/configuration/environment-variables/#tags
