### ISSUE TITLE
ERROR (Kamal::ConfigurationError): servers/web/options: should be a hash

### ISSUE THREAD

**Issue by wdiechmann** [basecamp/kamal#960]
why all of a sudden does Kamal start barfing like it's been getting paid in cash in Cairo and then couldn't resist licking it's fingers?

This deploy.yml has served me for close to a year now - afraid I didn't get the memo 😨 

```ruby
servers:
  web:
    hosts:
      - 4.4.4.4
    options:
      # "add-host": host.docker.internal:host-gateway
      # network: "mortimer"    
    labels:
      traefik.enable: true
      traefik.http.routers.mortimer.entrypoints: websecure
      traefik.http.routers.mortimer.rule: Host(`app.somedomain.com`) || Host(`bellis.somedomain.com`)
      traefik.http.routers.mortimer.tls.certresolver: letsencrypt
      traefik.http.routers.mortimer.tls.domains[0].main: app.somedomain.com
      traefik.http.routers.mortimer.tls.domains[0].sans: app.somedomain.com
      traefik.http.routers.mortimer.tls.domains[1].main: bellis.somedomain.com
      traefik.http.routers.mortimer.tls.domains[1].sans: bellis.somedomain.com
```

Here is what Kamal 1.8.3 thinks of that:

```bash
bootstrap.sh
letsencrypt
mortimer-anemone-redis
  ERROR (Kamal::ConfigurationError): servers/web/options: should be a hash
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validator.rb:117:in `error'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validator.rb:121:in `type_error'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validator.rb:113:in `validate_type!'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validator.rb:34:in `block (2 levels) in validate_against_example!'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validator.rb:135:in `with_context'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validator.rb:22:in `block in validate_against_example!'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validator.rb:20:in `each'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validator.rb:20:in `validate_against_example!'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validator.rb:11:in `validate!'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validator/role.rb:8:in `validate!'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/validation.rb:21:in `validate!'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/role.rb:14:in `initialize'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/servers.rb:11:in `new'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/servers.rb:11:in `block in initialize'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/servers.rb:11:in `map'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration/servers.rb:11:in `initialize'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration.rb:53:in `new'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration.rb:53:in `initialize'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration.rb:22:in `new'
/Users/walther/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/kamal-1.8.3/lib/kamal/configuration.rb:22:in `create_from'
/Users/walt
```

**Comment by wdiechmann** [comment]
not sure where to leave this - so I dump it here guessing that whilst the rest of the world is holding its breath until Nov 4th or rummages through Toronto in the quest for the holy cup (the one that Saint David used whilst spilling their neuron overweight) no one will notice that I stumbled on what I'd say clearly is a "bug" - 

How to fix it? `options: {}` as in

```ruby
servers:
  web:
    hosts:
      - 4.4.4.4
    options: {}
      # "add-host": host.docker.internal:host-gateway
      # network: "mortimer"    

```
